spring:
  datasource:
    url: jdbc:mysql://taskmanagement.cmhhpa2eubcb.us-east-1.rds.amazonaws.com:3306/taskmanagement
    username: admin
    password: patatavoladora
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect